SET SERVEROUTPUT ON;

DECLARE
    CNAME VARCHAR(50);
    VINNO VARCHAR(25);
    VPRICE DECIMAL(9, 2);
    CURSOR A IS
        SELECT C.CUSTOMER_NAME, V.VIN, V.PRICE
        FROM CUSTOMER C
        INNER JOIN VEHICLE_SALES VS ON C.CUSTOMER_ID = VS.CUSTOMER_ID
        INNER JOIN VEHICLE V ON VS.VIN = V.VIN
        WHERE V.PRICE >= 300000;

BEGIN

OPEN A;
FETCH A INTO CNAME, VINNO, VPRICE;

LOOP

DBMS_OUTPUT.PUT_LINE('CUSTOMER NAME: ' || CNAME);
DBMS_OUTPUT.PUT_LINE('VIN: ' || VINNO);
DBMS_OUTPUT.PUT_LINE('PRICE: R' || VPRICE);

FETCH A INTO CNAME, VINNO, VPRICE;
EXIT WHEN A%NOTFOUND;

END LOOP;

CLOSE A;

END;