SELECT (S.FIRSTNAME || ', ' || S.SURNAME) AS "NAMES", C.COURSENAME AS "COURSE", (R.RESULTS || '%') AS "RESULTS"
FROM STUDENT S
INNER JOIN RESULTS R ON s.studid = r.studid
INNER JOIN COURSE C ON c.courseid = r.courseid;