SET SERVEROUTPUT ON;

DECLARE
    ID VARCHAR(25);
    NUMRECORDS INT;
    CURSOR A IS
        SELECT STUDID, COUNT(RESULTID)
        FROM RESULTS
        GROUP BY STUDID
        ORDER BY COUNT(RESULTID) DESC;
        
BEGIN

OPEN A;
FETCH A INTO ID, NUMRECORDS;

LOOP

DBMS_OUTPUT.PUT_LINE('The result count for ' || ID || ' IS: ' || NUMRECORDS);
FETCH A INTO ID, NUMRECORDS;
EXIT WHEN A%NOTFOUND;

END LOOP;

CLOSE A;

END;