CREATE TABLE EVENT (
EVENT_ID CHAR(4) PRIMARY KEY NOT NULL,
EVENT_NAME VARCHAR(100) NOT NULL,
EVENT_RATE INT NOT NULL
);
/
CREATE TABLE ARTIST (
ARTIST_ID CHAR(5) PRIMARY KEY NOT NULL,
ARTIST_NAME VARCHAR(100) NOT NULL,
ARTIST_EMAIL VARCHAR(25) NOT NULL
);
/
CREATE TABLE BOOKINGS (
BOOKING_ID INT PRIMARY KEY NOT NULL,
BOOKING_DATE DATE NOT NULL,
EVENT_ID CHAR(4),
ARTIST_ID CHAR(5),
CONSTRAINT FK_EVENT_ID FOREIGN KEY (EVENT_ID) REFERENCES EVENT(EVENT_ID),
CONSTRAINT FK_ARTIST_ID FOREIGN KEY (ARTIST_ID) REFERENCES ARTIST(ARTIST_ID)
);
/