SET SERVEROUTPUT ON;

DECLARE
    NAME VARCHAR(100);
    PRICE INT;
    CURSOR A IS SELECT EVENT_NAME, EVENT_RATE
        FROM EVENT;

BEGIN

OPEN A;

FETCH A INTO NAME, PRICE;

IF PRICE > 250 THEN
    PRICE := PRICE * 0.9;
END IF;

LOOP

DBMS_OUTPUT.PUT_LINE(NAME || ' price: R ' || PRICE);
DBMS_OUTPUT.PUT_LINE('---------------------------------------');
FETCH A INTO NAME, PRICE;

IF PRICE > 250 THEN
    PRICE := PRICE * 0.9;
END IF;
    
EXIT WHEN A%NOTFOUND;

END LOOP;

CLOSE A;

END;