SET SERVEROUTPUT ON;

DECLARE
    EVENT VARCHAR(50);
    PRICE DECIMAL(5, 2);
    CURSOR A IS
        SELECT EVENT_NAME, EVENT_RATE
        FROM EVENT
        WHERE EVENT_RATE > (SELECT AVG(EVENT_RATE) FROM EVENT);
    
BEGIN

OPEN A;
FETCH A INTO EVENT, PRICE;

LOOP

DBMS_OUTPUT.PUT_LINE (EVENT);
DBMS_OUTPUT.PUT_LINE('Price: R ' || PRICE);
DBMS_OUTPUT.PUT_LINE('-----------------------------');

FETCH A INTO EVENT, PRICE;
EXIT WHEN A%NOTFOUND;

END LOOP;

CLOSE A;

END;