SET SERVEROUTPUT ON;

DECLARE
    NAME VARCHAR(50);
    BOOKING_DATE VARCHAR(25);
    CURSOR A IS
        SELECT A.ARTIST_NAME, B.BOOKING_DATE
        FROM ARTIST A
        INNER JOIN BOOKINGS B ON A.ARTIST_ID = B.ARTIST_ID
        INNER JOIN EVENT E ON B.EVENT_ID = E.EVENT_ID
        WHERE E.EVENT_ID = '1001';

BEGIN

OPEN A;
FETCH A INTO NAME, BOOKING_DATE;

LOOP

DBMS_OUTPUT.PUT_LINE('ARTIST NAME: ' || NAME);
DBMS_OUTPUT.put_line('BOOKING DATE: ' || BOOKING_DATE);

FETCH A INTO NAME, BOOKING_DATE;
EXIT WHEN A%NOTFOUND;

END LOOP;

CLOSE A;

END;