SELECT A.*
FROM
    (SELECT A.ARTIST_NAME, COUNT(B.BOOKING_ID) AS "PERFORMANCE_COUNT"
    FROM ARTIST A
    INNER JOIN BOOKINGS B ON A.ARTIST_ID = B.ARTIST_ID
    INNER JOIN EVENT E ON B.EVENT_ID = E.EVENT_ID
    GROUP BY A.ARTIST_NAME
    ORDER BY COUNT(B.BOOKING_ID) ASC) A
WHERE ROWNUM = 1;
