SET SERVEROUTPUT ON

DECLARE
    CRIMINAL VARCHAR(100);
    OFFENCE VARCHAR(50);
    SENTENCE VARCHAR(50);
    CURSOR A IS SELECT
        (C.CRIMINAL_FNAME || ', ' || CRIMINAL_SNAME),
        O.OFFENCE_NAME, O.OFFENCE_SENTENCE
        FROM CRIMINAL C
        INNER JOIN CASES CA ON C.CRIMINAL_ID = CA.CRIMINAL_ID
        INNER JOIN OFFENCE O ON CA.OFFENCE_ID = O.OFFENCE_ID
        WHERE O.OFFENCE_SENTENCE = '20 years';

BEGIN

OPEN A;
FETCH A INTO CRIMINAL, OFFENCE, SENTENCE;

LOOP

DBMS_OUTPUT.PUT_LINE ('CRIMINAL: ' || CRIMINAL);
DBMS_OUTPUT.PUT_LINE ('OFFENCE: ' || OFFENCE);
DBMS_OUTPUT.PUT_LINE ('SENTENCE: ' || SENTENCE);
DBMS_OUTPUT.PUT_LINE ('');

FETCH A INTO CRIMINAL, OFFENCE, SENTENCE;
EXIT WHEN A%NOTFOUND;

END LOOP;

CLOSE A;

END;