CREATE OR REPLACE FUNCTION Case_Adjustments
(Crim_ID IN VARCHAR2)
RETURN VARCHAR2
AS

OUTPUT VARCHAR2(200);
NEW_DATE DATE;
OLD_DATE DATE;
NAME VARCHAR2(50);
OFFENCE VARCHAR2(25);

BEGIN

SELECT CA.CASE_DATE, (C.CRIMINAL_FNAME || ', ' || C.CRIMINAL_SNAME),
    O.OFFENCE_NAME INTO OLD_DATE, NAME, OFFENCE
FROM CRIMINAL C
INNER JOIN CASES CA ON C.CRIMINAL_ID = CA.CRIMINAL_ID
INNER JOIN OFFENCE O ON O.OFFENCE_ID = CA.OFFENCE_ID
WHERE C.CRIMINAL_ID = Crim_ID;

NEW_DATE := OLD_DATE + 5;

OUTPUT := NAME || ' committed the offence ' || OFFENCE || ' and has a new case date which is ' || NEW_DATE;

RETURN OUTPUT;

EXCEPTION WHEN NO_DATA_FOUND THEN
    RAISE_APPLICATION_ERROR(-20100, 'No Criminal With Provided Criminal ID Was Found!');

END;

/

SELECT Case_Adjustments('crim101') AS "OUTPUT"
FROM DUAL;