SET SERVEROUTPUT ON;

DECLARE
    CRIMINAL VARCHAR2(50);
    OFFENCE VARCHAR2(25);
    RATING INT;
    OUTCOME VARCHAR2(25);
    CURSOR A IS
        SELECT (C.CRIMINAL_FNAME || ', ' || C.CRIMINAL_SNAME),
            O.OFFENCE_NAME, O.OFFENCE_RATING
        FROM CRIMINAL C
        INNER JOIN CASES CA ON CA.CRIMINAL_ID = C.CRIMINAL_ID
        INNER JOIN OFFENCE O ON CA.OFFENCE_ID = O.OFFENCE_ID;
    
BEGIN

OPEN A;
FETCH A INTO CRIMINAL, OFFENCE, RATING;

LOOP

IF RATING <= 5 THEN
    OUTCOME := 'Light offence';
ELSE
    OUTCOME := 'Serious offence';
END IF;

DBMS_OUTPUT.put_line('CRIMINAL: ' || CRIMINAL);
DBMS_OUTPUT.put_line('OFFENCE: ' || OFFENCE);
DBMS_OUTPUT.put_line('RATING: ' || RATING);
DBMS_OUTPUT.put_line('OUTCOME: ' || OUTCOME);
DBMS_OUTPUT.put_line('-------------------------');

FETCH A INTO CRIMINAL, OFFENCE, RATING;
EXIT WHEN A%NOTFOUND;

END LOOP;

CLOSE A;

END;