CREATE OR REPLACE FUNCTION Case_Adjustments
(CR_ID IN VARCHAR)
RETURN DATE AS

OLD_DATE DATE;
NEW_DATE DATE;

BEGIN

SELECT CASE_DATE INTO OLD_DATE
FROM CASES
WHERE CRIMINAL_ID = CR_ID;

NEW_DATE := OLD_DATE + 5;



RETURN NEW_DATE;

END;

/

SET SERVEROUTPUT ON;

DECLARE
    CRIMINAL VARCHAR(50);
    CRIME VARCHAR(50);
    
BEGIN

SELECT (C.CRIMINAL_FNAME || ', ' || C.CRIMINAL_SNAME),
    O.OFFENCE_NAME INTO CRIMINAL, CRIME
    FROM CRIMINAL C
    INNER JOIN CASES CA ON C.CRIMINAL_ID = CA.CRIMINAL_ID
    INNER JOIN OFFENCE O ON CA.OFFENCE_ID = O.OFFENCE_ID
    WHERE C.CRIMINAL_ID = 'crim101';

DBMS_OUTPUT.PUT_LINE(CRIMINAL || ' committed the offence ' || CRIME || ' and has a new case date which is ' || Case_Adjustments('crim101'));

END;