CREATE OR REPLACE TRIGGER Offence_Entry
AFTER INSERT ON OFFENCE
FOR EACH ROW

BEGIN

IF (:NEW.OFFENCE_RATING < 0 OR :NEW.OFFENCE_RATING > 10) THEN
    RAISE_APPLICATION_ERROR(-20001, 'Offence Rating Cannot Be Less Than 0 Or Greater Than 10.');
END IF;

END;

/

INSERT INTO OFFENCE VALUES ('33867', 'House Robbery', '50 years', 50);