CREATE OR REPLACE TRIGGER Offence_Entry
AFTER INSERT OR UPDATE OF OFFENCE_RATING ON OFFENCE
FOR EACH ROW

DECLARE

RATING INT;

BEGIN

RATING := :NEW.OFFENCE_RATING;

IF (RATING < 0) THEN
    RAISE_APPLICATION_ERROR(-20100, 'Offence Rating Cannot Be Less Than Zero (0).');
ELSIF (RATING > 10) THEN
    RAISE_APPLICATION_ERROR(-20100, 'Offence Rating Cannot Be More Than Ten (10).');
END IF;

END;

/

INSERT INTO OFFENCE VALUES ('33318', 'House Robbery', '2 years', 80);