CREATE OR REPLACE PROCEDURE Criminal_Details
(Crim_ID IN VARCHAR2) AS

NO_DATA EXCEPTION;
NAME VARCHAR2(50);
OFFENCE VARCHAR2(50);
OFFENCE_DATE DATE;
CURSOR A IS
    SELECT (C.CRIMINAL_FNAME || ' ' || C.CRIMINAL_SNAME),
        O.OFFENCE_NAME, CA.CASE_DATE
    FROM CRIMINAL C
    INNER JOIN CASES CA ON C.CRIMINAL_ID = CA.CRIMINAL_ID
    INNER JOIN OFFENCE O ON O.OFFENCE_ID = CA.OFFENCE_ID
    WHERE C.CRIMINAL_ID = Crim_ID;

BEGIN

OPEN A;
FETCH A INTO NAME, OFFENCE, OFFENCE_DATE;

IF A%ROWCOUNT = 0 THEN
    RAISE NO_DATA;
END IF;

LOOP

DBMS_OUTPUT.PUT_LINE ('CRIMINAL DETAILS: ' || NAME || ' committed a ' || OFFENCE || ' on the ' || OFFENCE_DATE);
DBMS_OUTPUT.PUT_LINE ('');

FETCH A INTO NAME, OFFENCE, OFFENCE_DATE;
EXIT WHEN A%NOTFOUND;

END LOOP;

EXCEPTION WHEN NO_DATA THEN
    RAISE_APPLICATION_ERROR(-20100, 'No Records Found For Criminal ID Provided.');

CLOSE A;

END;

/

EXECUTE Criminal_Details('crim101');