SET SERVEROUTPUT ON;

DECLARE
    CRIMINAL VARCHAR(50);
    OFFENCE VARCHAR(50);
    RATING INT;
    OUTCOME VARCHAR(50);
    CURSOR A IS SELECT
        (C.CRIMINAL_FNAME || ', ' || C.CRIMINAL_SNAME),
        O.OFFENCE_NAME, O.OFFENCE_RATING
        FROM CRIMINAL C
        INNER JOIN CASES CA ON C.CRIMINAL_ID = CA.CRIMINAL_ID
        INNER JOIN OFFENCE O ON O.OFFENCE_ID = CA.OFFENCE_ID;

BEGIN

OPEN A;
FETCH A INTO CRIMINAL, OFFENCE, RATING;

LOOP

IF RATING > 5 THEN
    OUTCOME := 'Serious Offence';
ELSE
    OUTCOME := 'Light Offence';
END IF;

DBMS_OUTPUT.put_line('CRIMINAL: ' || CRIMINAL);
DBMS_OUTPUT.put_line('OFFENCE:  ' || OFFENCE);
DBMS_OUTPUT.put_line('RATING:   ' || RATING);
DBMS_OUTPUT.put_line('OUTCOME:  ' || OUTCOME);
DBMS_OUTPUT.put_line('----------------------------');

FETCH A INTO CRIMINAL, OFFENCE, RATING;
EXIT WHEN A%NOTFOUND;

END LOOP;

END;