SET SERVEROUTPUT ON;

DECLARE
    STUDID VARCHAR(25);
    NORESULTS INT;
    CURSOR A IS
        SELECT STUDID, COUNT(RESULTID)
        FROM RESULTS
        GROUP BY STUDID
        ORDER BY COUNT(RESULTID) DESC;
    
BEGIN

OPEN A;
FETCH A INTO STUDID, NORESULTS;

LOOP

DBMS_OUTPUT.PUT_LINE('The result count for ' || STUDID || ' is: ' || NORESULTS);

FETCH A INTO STUDID, NORESULTS;
EXIT WHEN A%NOTFOUND;

END LOOP;

CLOSE A;

END;