CREATE TRIGGER ON_ADD_VEHICLE
AFTER INSERT
    ON VEHICLE
    FOR EACH ROW

DECLARE
    username CHAR(6);

BEGIN

SELECT user INTO username
FROM DUAL;

INSERT INTO REPORT(user_name, vin, date_added)
VALUES(username, :new.vin, SYSDATE);

END;

CREATE TABLE REPORT (

user_name VARCHAR(25) NOT NULL,
vin CHAR(6) NOT NULL,
date_added DATE NOT NULL

);

DROP TRIGGER ON_ADD_VEHICLE;
DROP TABLE REPORT;

SELECT *
FROM REPORT;

SELECT *
FROM VEHICLE;

INSERT INTO VEHICLE
VALUES('100004', 'AUDI', 'A4', 250000);

DELETE FROM REPORT;
DELETE FROM VEHICLE WHERE vin = '100004';