-- CREATE A TRIGGER TO GIVE A REPORT IF SOMEONE DELETED AN EMPLOYEE --
CREATE OR REPLACE TRIGGER empDelete
AFTER DELETE
ON EMPLOYEE
FOR EACH ROW
DECLARE
  v_userName VARCHAR2(40);
  
BEGIN
-- GET THE USERNAME OF THE PERSON DELETING THE OBJECT --
-- AND SAVE INTO THE REPORT TABLE --
SELECT user INTO v_userName
FROM DUAL;
-- NOW INSERT THIS INFO INTO THE REPORT TABLE --

INSERT INTO employee_audit (ID, SALARY, DELETE_DATE, DELETED_BY)
VALUES (:old.id, :old.salary, sysdate, v_userName);

END;

SELECT *
FROM EMPLOYEE;

SELECT *
FROM EMPLOYEE_AUDIT;

DELETE
FROM EMPLOYEE
WHERE ID = 01;