CREATE TABLE STUDENT (
STUDID CHAR(4) PRIMARY KEY NOT NULL,
FIRSTNAME VARCHAR(25) NOT NULL,
SURNAME VARCHAR(35) NOT NULL,
EMAIL VARCHAR(25) NOT NULL
);

/

CREATE TABLE COURSE (
COURSEID INT PRIMARY KEY NOT NULL,
COURSENAME VARCHAR(25) NOT NULL,
CREDITS INT NOT NULL
);

/

CREATE TABLE RESULTS (
RESULTID CHAR(3) PRIMARY KEY NOT NULL,
RESULTS INT NOT NULL,
STUDID CHAR(4),
COURSEID INT,
CONSTRAINT FK_STUDID FOREIGN KEY (STUDID) REFERENCES STUDENT(STUDID),
CONSTRAINT FK_COURSEID FOREIGN KEY (COURSEID) REFERENCES COURSE(COURSEID)
);

/