SELECT C.COMPANYNAME, P.PRODUCT, ('R ' || (S.QUANTITY * PRICE)) AS "TOTAL",
('R ' || (S.QUANTITY * PRICE * 0.1)) AS "DISCOUNT",
('R ' || (S.QUANTITY * PRICE * 0.9)) AS "DISCOUNTED_TOTAL"
FROM CUSTOMER C
INNER JOIN SALES S ON C.CUSTOMERID = S.CUSTOMERID
INNER JOIN PRODUCT P ON S.PRODUCTID = P.PRODUCTID;