SET SERVEROUTPUT ON;

DECLARE
    SALESAMT DECIMAL(8, 2);
    NAME VARCHAR(25);
    CURSOR A IS
        SELECT P.PRODUCT, SUM(P.PRICE * S.QUANTITY)
        FROM PRODUCT P
        INNER JOIN SALES S ON P.PRODUCTID = S.PRODUCTID
        WHERE P.PRODUCTID = 'X500'
        GROUP BY P.PRODUCT;
            
BEGIN

OPEN A;
FETCH A INTO NAME, SALESAMT;

LOOP

DBMS_OUTPUT.PUT_LINE('The total sales amount for product ' || NAME || ' is: R' || SALESAMT);

FETCH A INTO NAME, SALESAMT;
EXIT WHEN A%NOTFOUND;

END LOOP;

CLOSE A;

END;