SET SERVEROUTPUT ON;

DECLARE
    NAME VARCHAR(25);
    NOPURCHASES INT;
    CURSOR A IS
        SELECT C.COMPANYNAME, COUNT(S.SALEID)
        FROM CUSTOMER C
        INNER JOIN SALES S ON C.CUSTOMERID = S.CUSTOMERID
        GROUP BY C.COMPANYNAME;
        
BEGIN

OPEN A;
FETCH A INTO NAME, NOPURCHASES;

LOOP

DBMS_OUTPUT.PUT_LINE ('Purchases made by ' || NAME || ': ' || NOPURCHASES);

FETCH A INTO NAME, NOPURCHASES;
EXIT WHEN A%NOTFOUND;

END LOOP;

CLOSE A;

END;