CREATE OR REPLACE VIEW Booking_View
AS

SELECT BU.NUM_OF_PASSENGERS, C.CUST_ID, C.CUST_ADDRESS,
    L.LOCATION_PROVINCE, B.BOOKING_DATE
FROM BUS BU
INNER JOIN BOOKING B ON BU.VIN = B.VIN
INNER JOIN CUSTOMER C ON B.CUST_ID = C.CUST_ID
INNER JOIN LOCATIONS L ON L.LOCATION_ID = B.LOCATION_ID
WHERE B.BOOKING_DATE BETWEEN '20 June 2017' AND '25 June 2017'
ORDER BY C.CUST_ID DESC;

/

SELECT *
FROM Booking_View;