SELECT B.VIN, B.CUST_ID, L.LOCATION_NAME, B.BOOKING_DATE, C.CANCEL_REASON
FROM BOOKING B
INNER JOIN LOCATIONS L ON L.LOCATION_ID = B.LOCATION_ID
INNER JOIN CANCELLATIONS C ON C.BOOKING_ID = B.BOOKING_ID;