CREATE OR REPLACE PROCEDURE BUS_LOCATION_COUNT
(VIN_NO IN VARCHAR) AS

VIN VARCHAR(50);
NO_OF_LOCATIONS INT;
OUTPUT_COUNT VARCHAR(10);

BEGIN

SELECT COUNT(L.LOCATION_ID), B.VIN INTO NO_OF_LOCATIONS, VIN
FROM BOOKING B
INNER JOIN LOCATIONS L ON B.LOCATION_ID = L.LOCATION_ID
WHERE B.VIN = VIN_NO
GROUP BY B.VIN;

IF NO_OF_LOCATIONS = 0 THEN
    OUTPUT_COUNT := 'zero';
ELSIF NO_OF_LOCATIONS = 1 THEN
    OUTPUT_COUNT := 'one';
ELSIF NO_OF_LOCATIONS = 2 THEN
    OUTPUT_COUNT := 'two';
ELSIF NO_OF_LOCATIONS = 3 THEN
    OUTPUT_COUNT := 'three';
ELSE
    OUTPUT_COUNT := 'more than three';
END IF;
    
DBMS_OUTPUT.put_line('VIN: ' || VIN || ' has travelled to ' || OUTPUT_COUNT || ' locations.');

END;

/

EXECUTE BUS_LOCATION_COUNT('8235251524');