SET SERVEROUTPUT ON;

DECLARE
    CUSTOMER VARCHAR(100);
    VIN VARCHAR(50);
    BOOKING_DATE VARCHAR(50);
    LOCATION_PRICE DECIMAL(10, 2);
    DISCOUNT DECIMAL(10, 2);
    CURSOR A IS SELECT
        (C.CUST_FNAME || ', ' || C.CUST_SNAME),
        B.VIN, B.BOOKING_DATE, L.LOCATION_PRICE
        FROM CUSTOMER C
        INNER JOIN BOOKING B ON B.CUST_ID = C.CUST_ID
        INNER JOIN LOCATIONS L ON B.LOCATION_ID = L.LOCATION_ID;
    
BEGIN

OPEN A;
FETCH A INTO CUSTOMER, VIN, BOOKING_DATE, LOCATION_PRICE;

LOOP

IF LOCATION_PRICE >= 500 THEN
    DISCOUNT := LOCATION_PRICE * 0.1;
ELSE
    DISCOUNT := 0;
END IF;

DBMS_OUTPUT.PUT_LINE('CUSTOMER: ' || CUSTOMER);
DBMS_OUTPUT.PUT_LINE('VIN: ' || VIN);
DBMS_OUTPUT.PUT_LINE('BOOKING DATE: ' || BOOKING_DATE);
DBMS_OUTPUT.PUT_LINE('LOCATION PRICE: R' || LOCATION_PRICE);
DBMS_OUTPUT.PUT_LINE('DISCOUNT: R' || DISCOUNT);
DBMS_OUTPUT.PUT_LINE('--------------------------------');

FETCH A INTO CUSTOMER, VIN, BOOKING_DATE, LOCATION_PRICE;
EXIT WHEN A%NOTFOUND;

END LOOP;

CLOSE A;

END;