CREATE OR REPLACE TRIGGER New_Bus_Entry
AFTER INSERT OR UPDATE ON BUS FOR EACH ROW

DECLARE

BEGIN

IF :new.NUM_OF_PASSENGERS < 0 OR :new.NUM_OF_PASSENGERS > 200 THEN
    dbms_output.put_line('ERROR! NUMBER OF PASSENGERS MUST BE BETWEEN 0 AND 200.');
    RAISE_APPLICATION_ERROR(-2001, 'Error, The number of passengers must be between 0 and 200.');
END IF;

END;

/

INSERT INTO BUS VALUES (12345678910, 'Public Transport', 350, 'Yellow', 12345);