CREATE OR REPLACE TRIGGER New_Bus_Entry
AFTER INSERT OR UPDATE ON BUS
FOR EACH ROW

DECLARE

PASSENGERS INT;

BEGIN

PASSENGERS := :NEW.NUM_OF_PASSENGERS;

IF (PASSENGERS < 0 OR PASSENGERS > 200) THEN
    RAISE_APPLICATION_ERROR(-20001, 'Bus Must Contain Between Zero (0) and Two Hundred (200) Passengers.');
END IF;

END;

/

INSERT INTO BUS VALUES ('1234567890', 'Public Transport', 500, 'Red', 123456);