SET SERVEROUTPUT ON;

DECLARE
    CUSTOMER VARCHAR(50);
    VIN VARCHAR(50);
    BOOKING_DATE VARCHAR(50);
    LOCATION_PRICE DECIMAL(12, 2);
    DISCOUNT DECIMAL(12, 2);
    CURSOR A IS
        SELECT (C.CUST_FNAME || ', ' || C.CUST_SNAME),
            B.VIN, B.BOOKING_DATE, L.LOCATION_PRICE
        FROM CUSTOMER C
        INNER JOIN BOOKING B ON C.CUST_ID = B.CUST_ID
        INNER JOIN LOCATIONS L ON L.LOCATION_ID = B.LOCATION_ID;

BEGIN

OPEN A;
FETCH A INTO CUSTOMER, VIN, BOOKING_DATE, LOCATION_PRICE;

LOOP

IF LOCATION_PRICE >= 500 THEN
    DISCOUNT := LOCATION_PRICE * 0.1;
ELSE
    DISCOUNT := 0;
END IF;

DBMS_OUTPUT.put_line('CUSTOMER: ' || CUSTOMER);
DBMS_OUTPUT.put_line('VIN: ' || VIN);
DBMS_OUTPUT.put_line('BOOKING_DATE: ' || BOOKING_DATE);
DBMS_OUTPUT.put_line('LOCATION_PRICE: R' || LOCATION_PRICE);
DBMS_OUTPUT.put_line('DISCOUNT: R' || DISCOUNT);
DBMS_OUTPUT.put_line('-------------------------------------');

FETCH A INTO CUSTOMER, VIN, BOOKING_DATE, LOCATION_PRICE;
EXIT WHEN A%NOTFOUND;

END LOOP;

CLOSE A;

END;