SET SERVEROUTPUT ON;

DECLARE
    CUSTOMER VARCHAR(50);
    PRODUCT VARCHAR(50);
    CURSOR A IS
        SELECT (C.FIRST_NAME || ', ' || C.SURNAME), P.PRODUCT
        FROM CUSTOMER C
        INNER JOIN BILLING B ON C.CUSTOMER_ID = B.CUSTOMER_ID
        INNER JOIN PRODUCT_BILLING PB ON B.BILL_ID = PB.BILL_ID
        INNER JOIN PRODUCT P ON PB.PRODUCT_ID = P.PRODUCT_ID
        WHERE P.PRICE > 10000
        ORDER BY P.PRODUCT DESC;
    
BEGIN

OPEN A;
FETCH A INTO CUSTOMER, PRODUCT;

LOOP

DBMS_OUTPUT.PUT_LINE('CUSTOMER: ' || chr(9) || CUSTOMER);
DBMS_OUTPUT.PUT_LINE('PRODUCT: ' || chr(9) || PRODUCT);
DBMS_OUTPUT.PUT_LINE('--------------------------------------');

FETCH A INTO CUSTOMER, PRODUCT;
EXIT WHEN A %NOTFOUND;

END LOOP;

CLOSE A;

END;