SET SERVEROUTPUT ON;

DECLARE
    CUSTOMER VARCHAR(50);
    PRODUCT VARCHAR(50);
    REASON VARCHAR(100);
    CURSOR A IS
        SELECT (C.FIRST_NAME || ', ' || C.SURNAME), P.PRODUCT, R.REASON
        FROM CUSTOMER C
        INNER JOIN BILLING B ON C.CUSTOMER_ID = B.CUSTOMER_ID
        INNER JOIN PRODUCT_BILLING PB ON B.BILL_ID = PB.BILL_ID
        INNER JOIN PRODUCT P ON PB.PRODUCT_ID = P.PRODUCT_ID
        INNER JOIN RETURNS R ON PB.RETURN_ID = R.RETURN_ID
        ORDER BY R.REASON;
    
BEGIN

OPEN A;
FETCH A INTO CUSTOMER, PRODUCT, REASON;

LOOP

DBMS_OUTPUT.PUT_LINE('CUSTOMER: ' || chr(9) || chr(9) || CUSTOMER);
DBMS_OUTPUT.PUT_LINE('PRODUCT: ' || chr(9) || chr(9) || PRODUCT);
DBMS_OUTPUT.PUT_LINE('RETURN REASON: ' || ' ' || REASON);
DBMS_OUTPUT.PUT_LINE('---------------------------------------------------');

FETCH A INTO CUSTOMER, PRODUCT, REASON;
EXIT WHEN A %NOTFOUND;

END LOOP;

CLOSE A;

END;