CREATE OR REPLACE VIEW Inventory AS

SELECT PRODUCT, 'R' || PRICE AS "PRICE", QTY, 'R' || (PRICE * QTY) AS "STOCK VALUE"
FROM PRODUCT
WHERE (PRICE * QTY) > 100000
ORDER BY PRICE DESC, PRODUCT DESC;

SELECT *
FROM Inventory;