SET SERVEROUTPUT ON;

DECLARE
    PRODUCT VARCHAR(50);
    PRICE DECIMAL(9, 2);
    PRODUCT_TYPE VARCHAR(25);
    DESCRIPTION VARCHAR(100);
    DELIVERY_DAYS INT;
    CURSOR A IS
        SELECT P.PRODUCT, P.PRICE, D.DESCRIPTION, (D.DELIVERY_DATE - D.DISPATCH_DATE)
        FROM PRODUCT P
        INNER JOIN PRODUCT_BILLING PB ON P.PRODUCT_ID = PB.PRODUCT_ID
        INNER JOIN DELIVERY D ON PB.DELIVERY_ID = D.DELIVERY_ID
        WHERE (D.DELIVERY_DATE - D.DISPATCH_DATE) > 3
        ORDER BY P.PRODUCT DESC, D.DESCRIPTION;
    
BEGIN

OPEN A;
FETCH A INTO PRODUCT, PRICE, DESCRIPTION, DELIVERY_DAYS;

LOOP

IF PRICE >= 15000 THEN
    PRODUCT_TYPE := 'Premium Product';
ELSIF PRICE < 15000 THEN
    PRODUCT_TYPE := 'Non Premium Product';
END IF;

DBMS_OUTPUT.PUT_LINE('PRODUCT: ' || chr(9) || chr(9) || '  ' ||  PRODUCT);
DBMS_OUTPUT.PUT_LINE('PRICE:' || chr(9) || chr(9) || chr(9) || '  R' || PRICE);
DBMS_OUTPUT.PUT_LINE('DESCRIPTION: ' || chr(9) || '  ' || DESCRIPTION);
DBMS_OUTPUT.PUT_LINE('DELIVERY DAYS: ' || chr(9) || '  ' || DELIVERY_DAYS);
DBMS_OUTPUT.PUT_LINE('PRODUCT_CATEGORY: ' || PRODUCT_TYPE);
DBMS_OUTPUT.PUT_LINE('------------------------------------------------------------------');

FETCH A INTO PRODUCT, PRICE, DESCRIPTION, DELIVERY_DAYS;
EXIT WHEN A %NOTFOUND;

END LOOP;

CLOSE A;

END;
