SELECT V.MANUFACTURER, V.VEHICLE_MODEL AS "MODEL", V.PRICE, ('R ' || V.PRICE * 0.1) AS "COMMISSION",
       ('R ' || (V.PRICE * 1.1)) AS "TOTAL", C.CUSTOMER_NAME AS "CUSTOMER"
FROM VEHICLE V
INNER JOIN VEHICLE_SALES VS ON v.vin = vs.vin
INNER JOIN CUSTOMER C ON vs.customer_id = c.customer_id;