SELECT a.*
FROM
    (SELECT C.CUSTOMER_NAME, COUNT(V.CUSTOMER_ID) AS "PURCHASE_COUNT", ('R ' || SUM(PRICE)) AS "TOTAL"
     FROM CUSTOMER C
     INNER JOIN VEHICLE_SALES V ON c.customer_id = v.customer_id
     INNER JOIN VEHICLE VE ON v.vin = ve.vin
     GROUP BY C.CUSTOMER_NAME
     ORDER BY COUNT(V.CUSTOMER_ID) DESC
    ) a
WHERE ROWNUM = 1;
