CREATE TABLE VEHICLE (
VIN CHAR(6) PRIMARY KEY,
MANUFACTURER VARCHAR(25) NOT NULL,
VEHICLE_MODEL VARCHAR(25) NOT NULL,
PRICE DECIMAL(25, 2)
);

/

CREATE TABLE CUSTOMER (
CUSTOMER_ID CHAR(8) PRIMARY KEY,
CUSTOMER_NAME VARCHAR(25) NOT NULL,
CUSTOMER_EMAIL VARCHAR(25) NOT NULL
);

/

CREATE TABLE VEHICLE_SALES (
SALES_ID INT PRIMARY KEY,
SALES_DATE DATE NOT NULL,
VIN VARCHAR(25) NOT NULL,
CUSTOMER_ID CHAR(8)
CONSTRAINT FK_CUSTOMER_ID  REFERENCES CUSTOMER(CUSTOMER_ID)
);
