SET SERVEROUTPUT ON;

DECLARE
    PRODUCT VARCHAR(50);
    TOTAL DECIMAL(7, 2);
    CURSOR A IS
        SELECT P.PRODUCT, SUM((S.QUANTITY * P.PRICE))
        FROM PRODUCT P
        INNER JOIN SALES S ON P.PRODUCTID = S.PRODUCTID
        WHERE P.PRODUCTID = 'X500'
        GROUP BY P.PRODUCT;
    
BEGIN

OPEN A;
FETCH A INTO PRODUCT, TOTAL;

LOOP

DBMS_OUTPUT.PUT_LINE ('The total sales amount for product ' || PRODUCT || ' is: R' || TOTAL);

FETCH A INTO PRODUCT, TOTAL;
EXIT WHEN A%NOTFOUND;

END LOOP;

CLOSE A;

END;