SET SERVEROUTPUT ON;

DECLARE
    SUPPLIER VARCHAR(50);
    PRODUCT VARCHAR(50);
    PRICE DECIMAL(12, 2);
    CURSOR A IS SELECT S.SUPPLIERNAME,
        P.PRODUCTNAME, P.PRICE
        FROM SUPPLIER S
        INNER JOIN PRODUCT P ON S.SUPPLIERID = P.SUPPLIERID
        WHERE P.PRICE >= 5000;
        
BEGIN

OPEN A;
FETCH A INTO SUPPLIER, PRODUCT, PRICE;

LOOP

DBMS_OUTPUT.PUT_LINE('SUPPLIER:  ' || SUPPLIER);
DBMS_OUTPUT.PUT_LINE('PRODUCT:   ' || PRODUCT);
DBMS_OUTPUT.PUT_LINE('PRICE:     R ' || PRICE);
DBMS_OUTPUT.PUT_LINE('');

FETCH A INTO SUPPLIER, PRODUCT, PRICE;
EXIT WHEN A%NOTFOUND;

END LOOP;

CLOSE A;

END;