CREATE OR REPLACE TRIGGER ProductEntry
AFTER INSERT OR UPDATE ON PRODUCT
FOR EACH ROW

BEGIN

IF (:NEW.PRICE <= 0) THEN
    RAISE_APPLICATION_ERROR(-20001, 'Product Price Cannot Be Less Than Or Equal To 0.');
END IF;

END;

/

INSERT INTO PRODUCT VALUES ('Prod116', '100 Inch OLED', 0, '1 year', '751');