SET SERVEROUTPUT ON;

DECLARE
    EMPLOYEE VARCHAR(50);
    SALE_QTY INT;
    CURSOR A IS
        SELECT (E.FIRST_NAME || ', ' || E.SURNAME),
            S.SALEQTY AS "SALE QTY"
        FROM EMPLOYEE E
        INNER JOIN SALES S ON E.EMPID = S.EMPID
        WHERE S.SALEQTY <= 2 AND S.SALEQTY > 0;
    
BEGIN

OPEN A;
FETCH A INTO EMPLOYEE, SALE_QTY;

LOOP

DBMS_OUTPUT.PUT_LINE('EMPLOYEE: ' || EMPLOYEE);
DBMS_OUTPUT.PUT_LINE('SALE QTY: ' || SALE_QTY);
DBMS_OUTPUT.PUT_LINE('-------------------------');

FETCH A INTO EMPLOYEE, SALE_QTY;
EXIT WHEN A%NOTFOUND;

END LOOP;

END;