CREATE OR REPLACE VIEW Supplier_Warranty AS

SELECT S.SUPPLIERNAME AS "SUPPLIER_NAME",
    P.PRODUCTNAME AS "PRODUCT_NAME", P.WARRANTY
FROM SUPPLIER S
INNER JOIN PRODUCT P ON P.SUPPLIERID = S.SUPPLIERID
WHERE P.WARRANTY = '2 years';

/

SELECT *
FROM Supplier_Warranty;