CREATE TABLE STUDENT (
StudentID CHAR(3) PRIMARY KEY NOT NULL,
StudentName VARCHAR(25) NOT NULL,
Email VARCHAR(25) NOT NULL
);

/

CREATE TABLE MODULE (
Mod_ID CHAR(3) PRIMARY KEY NOT NULL,
Mod_Name VARCHAR(25) NOT NULL
);

/

CREATE TABLE RESULT (
ResultID INT PRIMARY KEY NOT NULL,
Results INT NOT NULL,
StudentID CHAR(3),
Mod_ID CHAR(3),
CONSTRAINT FK_Student_ID FOREIGN KEY (StudentID) REFERENCES STUDENT(StudentID),
CONSTRAINT FK_Mod_ID FOREIGN KEY (Mod_ID) REFERENCES MODULE(Mod_ID)
);

/
