INSERT INTO STUDENT VALUES ('101', 'JB', 'jb@gmail.com');
INSERT INTO STUDENT VALUES ('102', 'CL', 'cl@yahoo.com');
INSERT INTO STUDENT VALUES ('103', 'AN', 'an@gmail.com');

INSERT INTO MODULE VALUES ('555', 'Intro to programming');
INSERT INTO MODULE VALUES ('556', 'Intro to statistics');
INSERT INTO MODULE VALUES ('557', 'Intro to accounting');

INSERT INTO RESULT VALUES (1, 55, '101', '557');
INSERT INTO RESULT VALUES (2, 57, '103', '557');
INSERT INTO RESULT VALUES (3, 85, '101', '555');