SET SERVEROUTPUT ON;

DECLARE
  MAXIMUM INT;
  MINIMUM INT;
  COUNTRECORDS INT;
  AVERAGE DECIMAL(25, 2);
  SUMRESULT INT;
  
BEGIN

SELECT MAX(RESULTS), MIN(RESULTS), COUNT(RESULTS), AVG(RESULTS), SUM(RESULTS)
INTO MAXIMUM, MINIMUM, COUNTRECORDS, AVERAGE, SUMRESULT
FROM RESULT;

dbms_output.put_line('MAX RESULT: ' || MAXIMUM);
dbms_output.put_line('MIN RESULT: ' || MINIMUM);
dbms_output.put_line('COUNT RESULT: ' || COUNTRECORDS);
dbms_output.put_line('AVG RESULT: ' || AVERAGE);
dbms_output.put_line('SUM RESULT: ' || SUMRESULT);

END;