SET SERVEROUTPUT ON;

DECLARE
  ID VARCHAR(25);
  RESULT INT;
  MODULE VARCHAR(25);

BEGIN

SELECT S.STUDENTID, R.RESULTS, M.MOD_NAME INTO ID, RESULT, MODULE
FROM STUDENT S
INNER JOIN RESULT R ON S.STUDENTID = R.STUDENTID
INNER JOIN MODULE M ON M.MOD_ID = R.MOD_ID
WHERE S.STUDENTID = '101' AND M.MOD_ID = '557';

dbms_output.put_line('STUDENT ID: ' || ID);
dbms_output.put_line('RESULT: ' || RESULT || '%');
dbms_output.put_line('MODULE: ' || MODULE);

END;