SET SERVEROUTPUT ON;

DECLARE
  NAME VARCHAR(25);
  RESULT DECIMAL(25, 2);

BEGIN

SELECT S.STUDENTNAME, R.RESULTS INTO NAME, RESULT
FROM STUDENT S
INNER JOIN RESULT R ON S.STUDENTID = R.STUDENTID
WHERE R.RESULTID = 2;

RESULT := RESULT * 1.1;

dbms_output.put_line('STUDENT NAME: ' || NAME);
dbms_output.put_line('NEW RESULT: ' || RESULT);

END;