SELECT A.* FROM (
    SELECT C.CUSTOMER_NAME, COUNT(VS.SALES_ID) AS "PURCHASE_COUNT", ('R ' || SUM(V.PRICE)) AS "TOTAL"
    FROM CUSTOMER C
    INNER JOIN VEHICLE_SALES VS ON C.CUSTOMER_ID = VS.CUSTOMER_ID
    INNER JOIN VEHICLE V ON VS.VIN = V.VIN
    GROUP BY C.CUSTOMER_NAME
    ORDER BY SUM(V.PRICE) DESC
) A
WHERE ROWNUM = 1;