SELECT V.MANUFACTURER, V.VEHICLE_MODEL AS "MODEL", ('R ' || V.PRICE) AS "PRICE",
('R ' || (PRICE * 0.1)) AS "COMMISSION", ('R ' || (PRICE * 1.1)) AS "TOTAL",
C.CUSTOMER_NAME AS "CUSTOMER"
FROM VEHICLE V
INNER JOIN VEHICLE_SALES VS ON V.VIN = VS.VIN
INNER JOIN CUSTOMER C ON VS.CUSTOMER_ID = C.CUSTOMER_ID;