
CREATE TABLE CUSTOMER (
	CUS_ID CHAR(6) PRIMARY KEY,
	CUS_FNAME VARCHAR(25) NOT NULL,
	CUS_LNAME VARCHAR(25) NOT NULL,
	CUS_ADDR_LINE_1 VARCHAR(50),
	CUS_ADDR_LINE_2 VARCHAR(50),
	CUS_ADDR_CITY VARCHAR(25),
	CUS_ADDR_POSTCODE CHAR(4)
);
/
CREATE TABLE EMPLOYEE (
	EMP_ID CHAR(6) PRIMARY KEY,
	EMP_FNAME VARCHAR(25) NOT NULL,
	EMP_LNAME VARCHAR(25) NOT NULL
);
/
CREATE TABLE ORDERS (
	ORDER_ID CHAR(6) PRIMARY KEY,
	ORDER_DATE VARCHAR(25) NOT NULL,
	CUS_ID CHAR(6) NOT NULL,
	EMP_ID CHAR(6) NOT NULL,
	CONSTRAINT FK_CUS_ID FOREIGN KEY(CUS_ID) REFERENCES CUSTOMER(CUS_ID),
	CONSTRAINT FK_EMP_ID FOREIGN KEY(EMP_ID) REFERENCES EMPLOYEE(EMP_ID)
);
/