SELECT C.CUS_ID, C.CUS_FNAME, C.CUS_LNAME, O.ORDER_DATE
FROM CUSTOMER C
LEFT JOIN ORDERS O ON c.cus_id = o.cus_id
UNION ALL
SELECT C.CUS_ID, C.CUS_FNAME, C.CUS_LNAME, O.ORDER_DATE
FROM CUSTOMER C
RIGHT JOIN ORDERS O ON c.cus_id = o.cus_id