SET SERVEROUTPUT ON;

DECLARE
    PRODUCT_NAME VARCHAR(50);
    TOTAL_SALES DECIMAL(12, 2);
    CURSOR A IS SELECT
        P.PRODUCTNAME, (S.SALEQTY * P.PRICE)
        FROM PRODUCT P
        INNER JOIN PRODUCT_SALES PS ON P.PRODUCTID = PS.PRODUCTID
        INNER JOIN SALES S ON PS.SALEID = S.SALEID
        WHERE (S.SALEQTY * P.PRICE) > (SELECT AVG(S.SALEQTY * P.PRICE)
                                        FROM PRODUCT P
                                        INNER JOIN PRODUCT_SALES PS ON P.PRODUCTID = PS.PRODUCTID
                                        INNER JOIN SALES S ON PS.SALEID = S.SALEID);
        
BEGIN

OPEN A;
FETCH A INTO PRODUCT_NAME, TOTAL_SALES;

LOOP

DBMS_OUTPUT.PUT_LINE ('PRODUCT NAME:    ' || PRODUCT_NAME);
DBMS_OUTPUT.PUT_LINE ('TOTAL SALES:     R ' || TOTAL_SALES);
DBMS_OUTPUT.PUT_LINE ('------------------------------------');

FETCH A INTO PRODUCT_NAME, TOTAL_SALES;
EXIT WHEN A%NOTFOUND;

END LOOP;

CLOSE A;

END;