CREATE OR REPLACE PROCEDURE Sale_Count
(EMP IN VARCHAR) AS

SALE_COUNT INT;
PERFORMANCE VARCHAR(25);

BEGIN

SELECT COUNT(S.EMPID) INTO SALE_COUNT
FROM SALES S
WHERE S.EMPID = EMP;

IF SALE_COUNT >= 3 THEN
    PERFORMANCE := 'Good';
ELSE
    PERFORMANCE := 'Poor';
END IF;

DBMS_OUTPUT.PUT_LINE('Sale count for employee is ' || SALE_COUNT);
DBMS_OUTPUT.PUT_LINE('Performance: ' || PERFORMANCE);


END;

/

EXECUTE Sale_Count('101');