SET SERVEROUTPUT ON;

DECLARE

    CUSTOMER VARCHAR(50);
    PRODUCT VARCHAR(50);
    PRICE DECIMAL(12, 2);
    RATING INT;
    CURSOR A IS SELECT
        (C.FIRST_NAME || ', ' || C.SURNAME),
        P.PRODUCTNAME, P.PRICE, SP.RATING
        FROM CUSTOMER C
        INNER JOIN SALES S ON C.CUSTOMERID = S.CUSTOMERID
        INNER JOIN PRODUCT_SALES PS ON S.SALEID = PS.SALEID
        INNER JOIN PRODUCT P ON PS.PRODUCTID = P.PRODUCTID
        INNER JOIN SUPPLIER SP ON P.SUPPLIERID = SP.SUPPLIERID
        WHERE SP.RATING = 7;
    
BEGIN

OPEN A;
FETCH A INTO CUSTOMER, PRODUCT, PRICE, RATING;

LOOP

DBMS_OUTPUT.PUT_LINE ('CUSTOMER:        ' || CUSTOMER);
DBMS_OUTPUT.PUT_LINE ('PRODUCT:         ' || PRODUCT);
DBMS_OUTPUT.PUT_LINE ('PRICE:           R ' || PRICE);
DBMS_OUTPUT.PUT_LINE ('SUPPLIER RATING: ' || RATING);
DBMS_OUTPUT.PUT_LINE ('---------------------------------');

FETCH A INTO CUSTOMER, PRODUCT, PRICE, RATING;
EXIT WHEN A%NOTFOUND;

END LOOP;

CLOSE A;

END;