CREATE OR REPLACE VIEW Overall_Report AS

SELECT (E.FIRST_NAME || ', ' || E.SURNAME) AS "EMPLOYEE", (C.FIRST_NAME || ', ' || C.SURNAME) AS "CUSTOMER",
    P.PRODUCTNAME AS "PRODUCT", SP.SUPPLIERNAME AS "SUPPLIER", S.SALEDATE AS "SALE_DATE"
FROM EMPLOYEE E
INNER JOIN SALES S ON E.EMPID = S.EMPID
INNER JOIN CUSTOMER C ON S.CUSTOMERID = C.CUSTOMERID
INNER JOIN PRODUCT_SALES PS ON S.SALEID = PS.SALEID
INNER JOIN PRODUCT P ON PS.PRODUCTID = P.PRODUCTID
INNER JOIN SUPPLIER SP ON P.SUPPLIERID = SP.SUPPLIERID
WHERE S.SALEDATE = '22/OCT/16';

/

SELECT *
FROM Overall_Report;